# Generated by Django 2.2.5 on 2020-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201221_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
